@notesURL = http://localhost:3030
#@notesURL = https://wom22-notes.azurewebsites.net

GET {{notesURL}}/

###

GET {{notesURL}}/notes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzI4NGU5YWYzZDM4ODNmOTUwNzkyODkiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2Mzc2MzQwNCwiZXhwIjoxNjYzNzYzNDY0fQ.WEoi_I2iD9OXDfI-fgBEioBxn_4PQjz1-tl4l2LuadE
### Hämta alla arkiverade notes
GET {{notesURL}}/notes/?archived=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzI4NGU5YWYzZDM4ODNmOTUwNzkyODkiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2MzU4OTE5NH0.tKYXgGK0ac66CXnGe7vy1gUUXI5NrqXbyPLuuGuBaEY


###

GET {{notesURL}}/notes/632af34be70a60687a47a32c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzI4NGU5YWYzZDM4ODNmOTUwNzkyODkiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2MzU4OTE5NH0.tKYXgGK0ac66CXnGe7vy1gUUXI5NrqXbyPLuuGuBaEY

###
DELETE {{notesURL}}/notes/632af34be70a60687a47a32c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzI4NGU5YWYzZDM4ODNmOTUwNzkyODkiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2MzU4OTE5NH0.tKYXgGK0ac66CXnGe7vy1gUUXI5NrqXbyPLuuGuBaEY

###
POST {{notesURL}}/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzI4NGU5YWYzZDM4ODNmOTUwNzkyODkiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2MzU4OTE5NH0.tKYXgGK0ac66CXnGe7vy1gUUXI5NrqXbyPLuuGuBaEY

{
    "text": "foo"
}

###
PATCH {{notesURL}}/notes/632af68c1f4c7a0269109d00
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzI4NGU5YWYzZDM4ODNmOTUwNzkyODkiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2MzU4OTE5NH0.tKYXgGK0ac66CXnGe7vy1gUUXI5NrqXbyPLuuGuBaEY

{
    "archived": true
}